OBJS += addons/textmode/kputch.o
OBJS += addons/textmode/cls.o
OBJS += addons/textmode/kputs.o
OBJS += addons/textmode/textmode.o
OBJS += addons/textmode/kputs_dec.o
OBJS += addons/textmode/kputs_hex.o
